// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	dto "github.com/guttosm/pack-service/internal/domain/dto"
	mock "github.com/stretchr/testify/mock"

	model "github.com/guttosm/pack-service/internal/domain/model"

	primitive "go.mongodb.org/mongo-driver/bson/primitive"
)

// MockAuthService is an autogenerated mock type for the AuthService type
type MockAuthService struct {
	mock.Mock
}

type MockAuthService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuthService) EXPECT() *MockAuthService_Expecter {
	return &MockAuthService_Expecter{mock: &_m.Mock}
}

// InvalidateToken provides a mock function with given fields: ctx, tokenString
func (_m *MockAuthService) InvalidateToken(ctx context.Context, tokenString string) error {
	ret := _m.Called(ctx, tokenString)

	if len(ret) == 0 {
		panic("no return value specified for InvalidateToken")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, tokenString)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAuthService_InvalidateToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InvalidateToken'
type MockAuthService_InvalidateToken_Call struct {
	*mock.Call
}

// InvalidateToken is a helper method to define mock.On call
//   - ctx context.Context
//   - tokenString string
func (_e *MockAuthService_Expecter) InvalidateToken(ctx interface{}, tokenString interface{}) *MockAuthService_InvalidateToken_Call {
	return &MockAuthService_InvalidateToken_Call{Call: _e.mock.On("InvalidateToken", ctx, tokenString)}
}

func (_c *MockAuthService_InvalidateToken_Call) Run(run func(ctx context.Context, tokenString string)) *MockAuthService_InvalidateToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockAuthService_InvalidateToken_Call) Return(_a0 error) *MockAuthService_InvalidateToken_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAuthService_InvalidateToken_Call) RunAndReturn(run func(context.Context, string) error) *MockAuthService_InvalidateToken_Call {
	_c.Call.Return(run)
	return _c
}

// InvalidateUserTokens provides a mock function with given fields: ctx, userID
func (_m *MockAuthService) InvalidateUserTokens(ctx context.Context, userID primitive.ObjectID) error {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for InvalidateUserTokens")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, primitive.ObjectID) error); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAuthService_InvalidateUserTokens_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InvalidateUserTokens'
type MockAuthService_InvalidateUserTokens_Call struct {
	*mock.Call
}

// InvalidateUserTokens is a helper method to define mock.On call
//   - ctx context.Context
//   - userID primitive.ObjectID
func (_e *MockAuthService_Expecter) InvalidateUserTokens(ctx interface{}, userID interface{}) *MockAuthService_InvalidateUserTokens_Call {
	return &MockAuthService_InvalidateUserTokens_Call{Call: _e.mock.On("InvalidateUserTokens", ctx, userID)}
}

func (_c *MockAuthService_InvalidateUserTokens_Call) Run(run func(ctx context.Context, userID primitive.ObjectID)) *MockAuthService_InvalidateUserTokens_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(primitive.ObjectID))
	})
	return _c
}

func (_c *MockAuthService_InvalidateUserTokens_Call) Return(_a0 error) *MockAuthService_InvalidateUserTokens_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAuthService_InvalidateUserTokens_Call) RunAndReturn(run func(context.Context, primitive.ObjectID) error) *MockAuthService_InvalidateUserTokens_Call {
	_c.Call.Return(run)
	return _c
}

// Login provides a mock function with given fields: ctx, email, password
func (_m *MockAuthService) Login(ctx context.Context, email string, password string) (*dto.TokenPair, *model.User, error) {
	ret := _m.Called(ctx, email, password)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 *dto.TokenPair
	var r1 *model.User
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*dto.TokenPair, *model.User, error)); ok {
		return rf(ctx, email, password)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *dto.TokenPair); ok {
		r0 = rf(ctx, email, password)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.TokenPair)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) *model.User); ok {
		r1 = rf(ctx, email, password)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*model.User)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, string) error); ok {
		r2 = rf(ctx, email, password)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockAuthService_Login_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Login'
type MockAuthService_Login_Call struct {
	*mock.Call
}

// Login is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
//   - password string
func (_e *MockAuthService_Expecter) Login(ctx interface{}, email interface{}, password interface{}) *MockAuthService_Login_Call {
	return &MockAuthService_Login_Call{Call: _e.mock.On("Login", ctx, email, password)}
}

func (_c *MockAuthService_Login_Call) Run(run func(ctx context.Context, email string, password string)) *MockAuthService_Login_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockAuthService_Login_Call) Return(_a0 *dto.TokenPair, _a1 *model.User, _a2 error) *MockAuthService_Login_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockAuthService_Login_Call) RunAndReturn(run func(context.Context, string, string) (*dto.TokenPair, *model.User, error)) *MockAuthService_Login_Call {
	_c.Call.Return(run)
	return _c
}

// Logout provides a mock function with given fields: ctx, accessToken, refreshToken
func (_m *MockAuthService) Logout(ctx context.Context, accessToken string, refreshToken string) error {
	ret := _m.Called(ctx, accessToken, refreshToken)

	if len(ret) == 0 {
		panic("no return value specified for Logout")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, accessToken, refreshToken)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAuthService_Logout_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Logout'
type MockAuthService_Logout_Call struct {
	*mock.Call
}

// Logout is a helper method to define mock.On call
//   - ctx context.Context
//   - accessToken string
//   - refreshToken string
func (_e *MockAuthService_Expecter) Logout(ctx interface{}, accessToken interface{}, refreshToken interface{}) *MockAuthService_Logout_Call {
	return &MockAuthService_Logout_Call{Call: _e.mock.On("Logout", ctx, accessToken, refreshToken)}
}

func (_c *MockAuthService_Logout_Call) Run(run func(ctx context.Context, accessToken string, refreshToken string)) *MockAuthService_Logout_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockAuthService_Logout_Call) Return(_a0 error) *MockAuthService_Logout_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAuthService_Logout_Call) RunAndReturn(run func(context.Context, string, string) error) *MockAuthService_Logout_Call {
	_c.Call.Return(run)
	return _c
}

// RefreshToken provides a mock function with given fields: ctx, refreshToken
func (_m *MockAuthService) RefreshToken(ctx context.Context, refreshToken string) (*dto.TokenPair, error) {
	ret := _m.Called(ctx, refreshToken)

	if len(ret) == 0 {
		panic("no return value specified for RefreshToken")
	}

	var r0 *dto.TokenPair
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*dto.TokenPair, error)); ok {
		return rf(ctx, refreshToken)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *dto.TokenPair); ok {
		r0 = rf(ctx, refreshToken)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.TokenPair)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, refreshToken)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAuthService_RefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RefreshToken'
type MockAuthService_RefreshToken_Call struct {
	*mock.Call
}

// RefreshToken is a helper method to define mock.On call
//   - ctx context.Context
//   - refreshToken string
func (_e *MockAuthService_Expecter) RefreshToken(ctx interface{}, refreshToken interface{}) *MockAuthService_RefreshToken_Call {
	return &MockAuthService_RefreshToken_Call{Call: _e.mock.On("RefreshToken", ctx, refreshToken)}
}

func (_c *MockAuthService_RefreshToken_Call) Run(run func(ctx context.Context, refreshToken string)) *MockAuthService_RefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockAuthService_RefreshToken_Call) Return(_a0 *dto.TokenPair, _a1 error) *MockAuthService_RefreshToken_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAuthService_RefreshToken_Call) RunAndReturn(run func(context.Context, string) (*dto.TokenPair, error)) *MockAuthService_RefreshToken_Call {
	_c.Call.Return(run)
	return _c
}

// Register provides a mock function with given fields: ctx, email, username, password, name
func (_m *MockAuthService) Register(ctx context.Context, email string, username string, password string, name string) (*dto.TokenPair, *model.User, error) {
	ret := _m.Called(ctx, email, username, password, name)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 *dto.TokenPair
	var r1 *model.User
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string) (*dto.TokenPair, *model.User, error)); ok {
		return rf(ctx, email, username, password, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string) *dto.TokenPair); ok {
		r0 = rf(ctx, email, username, password, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.TokenPair)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, string) *model.User); ok {
		r1 = rf(ctx, email, username, password, name)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*model.User)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, string, string, string) error); ok {
		r2 = rf(ctx, email, username, password, name)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockAuthService_Register_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Register'
type MockAuthService_Register_Call struct {
	*mock.Call
}

// Register is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
//   - username string
//   - password string
//   - name string
func (_e *MockAuthService_Expecter) Register(ctx interface{}, email interface{}, username interface{}, password interface{}, name interface{}) *MockAuthService_Register_Call {
	return &MockAuthService_Register_Call{Call: _e.mock.On("Register", ctx, email, username, password, name)}
}

func (_c *MockAuthService_Register_Call) Run(run func(ctx context.Context, email string, username string, password string, name string)) *MockAuthService_Register_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string), args[4].(string))
	})
	return _c
}

func (_c *MockAuthService_Register_Call) Return(_a0 *dto.TokenPair, _a1 *model.User, _a2 error) *MockAuthService_Register_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockAuthService_Register_Call) RunAndReturn(run func(context.Context, string, string, string, string) (*dto.TokenPair, *model.User, error)) *MockAuthService_Register_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateToken provides a mock function with given fields: ctx, tokenString
func (_m *MockAuthService) ValidateToken(ctx context.Context, tokenString string) (*dto.Claims, error) {
	ret := _m.Called(ctx, tokenString)

	if len(ret) == 0 {
		panic("no return value specified for ValidateToken")
	}

	var r0 *dto.Claims
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*dto.Claims, error)); ok {
		return rf(ctx, tokenString)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *dto.Claims); ok {
		r0 = rf(ctx, tokenString)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.Claims)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, tokenString)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAuthService_ValidateToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateToken'
type MockAuthService_ValidateToken_Call struct {
	*mock.Call
}

// ValidateToken is a helper method to define mock.On call
//   - ctx context.Context
//   - tokenString string
func (_e *MockAuthService_Expecter) ValidateToken(ctx interface{}, tokenString interface{}) *MockAuthService_ValidateToken_Call {
	return &MockAuthService_ValidateToken_Call{Call: _e.mock.On("ValidateToken", ctx, tokenString)}
}

func (_c *MockAuthService_ValidateToken_Call) Run(run func(ctx context.Context, tokenString string)) *MockAuthService_ValidateToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockAuthService_ValidateToken_Call) Return(_a0 *dto.Claims, _a1 error) *MockAuthService_ValidateToken_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAuthService_ValidateToken_Call) RunAndReturn(run func(context.Context, string) (*dto.Claims, error)) *MockAuthService_ValidateToken_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAuthService creates a new instance of MockAuthService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuthService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuthService {
	mock := &MockAuthService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
