// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	cache "github.com/guttosm/pack-service/internal/service/cache"
	mock "github.com/stretchr/testify/mock"

	model "github.com/guttosm/pack-service/internal/domain/model"
)

// MockCacheWithMetrics is an autogenerated mock type for the CacheWithMetrics type
type MockCacheWithMetrics struct {
	mock.Mock
}

type MockCacheWithMetrics_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCacheWithMetrics) EXPECT() *MockCacheWithMetrics_Expecter {
	return &MockCacheWithMetrics_Expecter{mock: &_m.Mock}
}

// Clear provides a mock function with no fields
func (_m *MockCacheWithMetrics) Clear() {
	_m.Called()
}

// MockCacheWithMetrics_Clear_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Clear'
type MockCacheWithMetrics_Clear_Call struct {
	*mock.Call
}

// Clear is a helper method to define mock.On call
func (_e *MockCacheWithMetrics_Expecter) Clear() *MockCacheWithMetrics_Clear_Call {
	return &MockCacheWithMetrics_Clear_Call{Call: _e.mock.On("Clear")}
}

func (_c *MockCacheWithMetrics_Clear_Call) Run(run func()) *MockCacheWithMetrics_Clear_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCacheWithMetrics_Clear_Call) Return() *MockCacheWithMetrics_Clear_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockCacheWithMetrics_Clear_Call) RunAndReturn(run func()) *MockCacheWithMetrics_Clear_Call {
	_c.Run(run)
	return _c
}

// Get provides a mock function with given fields: key
func (_m *MockCacheWithMetrics) Get(key int) (model.PackResult, bool) {
	ret := _m.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 model.PackResult
	var r1 bool
	if rf, ok := ret.Get(0).(func(int) (model.PackResult, bool)); ok {
		return rf(key)
	}
	if rf, ok := ret.Get(0).(func(int) model.PackResult); ok {
		r0 = rf(key)
	} else {
		r0 = ret.Get(0).(model.PackResult)
	}

	if rf, ok := ret.Get(1).(func(int) bool); ok {
		r1 = rf(key)
	} else {
		r1 = ret.Get(1).(bool)
	}

	return r0, r1
}

// MockCacheWithMetrics_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockCacheWithMetrics_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - key int
func (_e *MockCacheWithMetrics_Expecter) Get(key interface{}) *MockCacheWithMetrics_Get_Call {
	return &MockCacheWithMetrics_Get_Call{Call: _e.mock.On("Get", key)}
}

func (_c *MockCacheWithMetrics_Get_Call) Run(run func(key int)) *MockCacheWithMetrics_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int))
	})
	return _c
}

func (_c *MockCacheWithMetrics_Get_Call) Return(_a0 model.PackResult, _a1 bool) *MockCacheWithMetrics_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCacheWithMetrics_Get_Call) RunAndReturn(run func(int) (model.PackResult, bool)) *MockCacheWithMetrics_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Invalidate provides a mock function with given fields: key
func (_m *MockCacheWithMetrics) Invalidate(key int) {
	_m.Called(key)
}

// MockCacheWithMetrics_Invalidate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Invalidate'
type MockCacheWithMetrics_Invalidate_Call struct {
	*mock.Call
}

// Invalidate is a helper method to define mock.On call
//   - key int
func (_e *MockCacheWithMetrics_Expecter) Invalidate(key interface{}) *MockCacheWithMetrics_Invalidate_Call {
	return &MockCacheWithMetrics_Invalidate_Call{Call: _e.mock.On("Invalidate", key)}
}

func (_c *MockCacheWithMetrics_Invalidate_Call) Run(run func(key int)) *MockCacheWithMetrics_Invalidate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int))
	})
	return _c
}

func (_c *MockCacheWithMetrics_Invalidate_Call) Return() *MockCacheWithMetrics_Invalidate_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockCacheWithMetrics_Invalidate_Call) RunAndReturn(run func(int)) *MockCacheWithMetrics_Invalidate_Call {
	_c.Run(run)
	return _c
}

// Metrics provides a mock function with no fields
func (_m *MockCacheWithMetrics) Metrics() cache.Metrics {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Metrics")
	}

	var r0 cache.Metrics
	if rf, ok := ret.Get(0).(func() cache.Metrics); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(cache.Metrics)
	}

	return r0
}

// MockCacheWithMetrics_Metrics_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Metrics'
type MockCacheWithMetrics_Metrics_Call struct {
	*mock.Call
}

// Metrics is a helper method to define mock.On call
func (_e *MockCacheWithMetrics_Expecter) Metrics() *MockCacheWithMetrics_Metrics_Call {
	return &MockCacheWithMetrics_Metrics_Call{Call: _e.mock.On("Metrics")}
}

func (_c *MockCacheWithMetrics_Metrics_Call) Run(run func()) *MockCacheWithMetrics_Metrics_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCacheWithMetrics_Metrics_Call) Return(_a0 cache.Metrics) *MockCacheWithMetrics_Metrics_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCacheWithMetrics_Metrics_Call) RunAndReturn(run func() cache.Metrics) *MockCacheWithMetrics_Metrics_Call {
	_c.Call.Return(run)
	return _c
}

// Set provides a mock function with given fields: key, value
func (_m *MockCacheWithMetrics) Set(key int, value model.PackResult) {
	_m.Called(key, value)
}

// MockCacheWithMetrics_Set_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Set'
type MockCacheWithMetrics_Set_Call struct {
	*mock.Call
}

// Set is a helper method to define mock.On call
//   - key int
//   - value model.PackResult
func (_e *MockCacheWithMetrics_Expecter) Set(key interface{}, value interface{}) *MockCacheWithMetrics_Set_Call {
	return &MockCacheWithMetrics_Set_Call{Call: _e.mock.On("Set", key, value)}
}

func (_c *MockCacheWithMetrics_Set_Call) Run(run func(key int, value model.PackResult)) *MockCacheWithMetrics_Set_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int), args[1].(model.PackResult))
	})
	return _c
}

func (_c *MockCacheWithMetrics_Set_Call) Return() *MockCacheWithMetrics_Set_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockCacheWithMetrics_Set_Call) RunAndReturn(run func(int, model.PackResult)) *MockCacheWithMetrics_Set_Call {
	_c.Run(run)
	return _c
}

// Stop provides a mock function with no fields
func (_m *MockCacheWithMetrics) Stop() {
	_m.Called()
}

// MockCacheWithMetrics_Stop_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stop'
type MockCacheWithMetrics_Stop_Call struct {
	*mock.Call
}

// Stop is a helper method to define mock.On call
func (_e *MockCacheWithMetrics_Expecter) Stop() *MockCacheWithMetrics_Stop_Call {
	return &MockCacheWithMetrics_Stop_Call{Call: _e.mock.On("Stop")}
}

func (_c *MockCacheWithMetrics_Stop_Call) Run(run func()) *MockCacheWithMetrics_Stop_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCacheWithMetrics_Stop_Call) Return() *MockCacheWithMetrics_Stop_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockCacheWithMetrics_Stop_Call) RunAndReturn(run func()) *MockCacheWithMetrics_Stop_Call {
	_c.Run(run)
	return _c
}

// NewMockCacheWithMetrics creates a new instance of MockCacheWithMetrics. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCacheWithMetrics(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCacheWithMetrics {
	mock := &MockCacheWithMetrics{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
