// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	model "github.com/guttosm/pack-service/internal/domain/model"
	mock "github.com/stretchr/testify/mock"
)

// MockCache is an autogenerated mock type for the Cache type
type MockCache struct {
	mock.Mock
}

type MockCache_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCache) EXPECT() *MockCache_Expecter {
	return &MockCache_Expecter{mock: &_m.Mock}
}

// Clear provides a mock function with no fields
func (_m *MockCache) Clear() {
	_m.Called()
}

// MockCache_Clear_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Clear'
type MockCache_Clear_Call struct {
	*mock.Call
}

// Clear is a helper method to define mock.On call
func (_e *MockCache_Expecter) Clear() *MockCache_Clear_Call {
	return &MockCache_Clear_Call{Call: _e.mock.On("Clear")}
}

func (_c *MockCache_Clear_Call) Run(run func()) *MockCache_Clear_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCache_Clear_Call) Return() *MockCache_Clear_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockCache_Clear_Call) RunAndReturn(run func()) *MockCache_Clear_Call {
	_c.Run(run)
	return _c
}

// Get provides a mock function with given fields: key
func (_m *MockCache) Get(key int) (model.PackResult, bool) {
	ret := _m.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 model.PackResult
	var r1 bool
	if rf, ok := ret.Get(0).(func(int) (model.PackResult, bool)); ok {
		return rf(key)
	}
	if rf, ok := ret.Get(0).(func(int) model.PackResult); ok {
		r0 = rf(key)
	} else {
		r0 = ret.Get(0).(model.PackResult)
	}

	if rf, ok := ret.Get(1).(func(int) bool); ok {
		r1 = rf(key)
	} else {
		r1 = ret.Get(1).(bool)
	}

	return r0, r1
}

// MockCache_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockCache_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - key int
func (_e *MockCache_Expecter) Get(key interface{}) *MockCache_Get_Call {
	return &MockCache_Get_Call{Call: _e.mock.On("Get", key)}
}

func (_c *MockCache_Get_Call) Run(run func(key int)) *MockCache_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int))
	})
	return _c
}

func (_c *MockCache_Get_Call) Return(_a0 model.PackResult, _a1 bool) *MockCache_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCache_Get_Call) RunAndReturn(run func(int) (model.PackResult, bool)) *MockCache_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Invalidate provides a mock function with given fields: key
func (_m *MockCache) Invalidate(key int) {
	_m.Called(key)
}

// MockCache_Invalidate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Invalidate'
type MockCache_Invalidate_Call struct {
	*mock.Call
}

// Invalidate is a helper method to define mock.On call
//   - key int
func (_e *MockCache_Expecter) Invalidate(key interface{}) *MockCache_Invalidate_Call {
	return &MockCache_Invalidate_Call{Call: _e.mock.On("Invalidate", key)}
}

func (_c *MockCache_Invalidate_Call) Run(run func(key int)) *MockCache_Invalidate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int))
	})
	return _c
}

func (_c *MockCache_Invalidate_Call) Return() *MockCache_Invalidate_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockCache_Invalidate_Call) RunAndReturn(run func(int)) *MockCache_Invalidate_Call {
	_c.Run(run)
	return _c
}

// Set provides a mock function with given fields: key, value
func (_m *MockCache) Set(key int, value model.PackResult) {
	_m.Called(key, value)
}

// MockCache_Set_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Set'
type MockCache_Set_Call struct {
	*mock.Call
}

// Set is a helper method to define mock.On call
//   - key int
//   - value model.PackResult
func (_e *MockCache_Expecter) Set(key interface{}, value interface{}) *MockCache_Set_Call {
	return &MockCache_Set_Call{Call: _e.mock.On("Set", key, value)}
}

func (_c *MockCache_Set_Call) Run(run func(key int, value model.PackResult)) *MockCache_Set_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int), args[1].(model.PackResult))
	})
	return _c
}

func (_c *MockCache_Set_Call) Return() *MockCache_Set_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockCache_Set_Call) RunAndReturn(run func(int, model.PackResult)) *MockCache_Set_Call {
	_c.Run(run)
	return _c
}

// Stop provides a mock function with no fields
func (_m *MockCache) Stop() {
	_m.Called()
}

// MockCache_Stop_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stop'
type MockCache_Stop_Call struct {
	*mock.Call
}

// Stop is a helper method to define mock.On call
func (_e *MockCache_Expecter) Stop() *MockCache_Stop_Call {
	return &MockCache_Stop_Call{Call: _e.mock.On("Stop")}
}

func (_c *MockCache_Stop_Call) Run(run func()) *MockCache_Stop_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCache_Stop_Call) Return() *MockCache_Stop_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockCache_Stop_Call) RunAndReturn(run func()) *MockCache_Stop_Call {
	_c.Run(run)
	return _c
}

// NewMockCache creates a new instance of MockCache. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCache(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCache {
	mock := &MockCache{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
