// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/guttosm/pack-service/internal/domain/model"
	mock "github.com/stretchr/testify/mock"
)

// MockLoggingService is an autogenerated mock type for the LoggingService type
type MockLoggingService struct {
	mock.Mock
}

type MockLoggingService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLoggingService) EXPECT() *MockLoggingService_Expecter {
	return &MockLoggingService_Expecter{mock: &_m.Mock}
}

// CountLogs provides a mock function with given fields: ctx, opts
func (_m *MockLoggingService) CountLogs(ctx context.Context, opts model.LogQueryOptions) (int64, error) {
	ret := _m.Called(ctx, opts)

	if len(ret) == 0 {
		panic("no return value specified for CountLogs")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.LogQueryOptions) (int64, error)); ok {
		return rf(ctx, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.LogQueryOptions) int64); ok {
		r0 = rf(ctx, opts)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.LogQueryOptions) error); ok {
		r1 = rf(ctx, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockLoggingService_CountLogs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountLogs'
type MockLoggingService_CountLogs_Call struct {
	*mock.Call
}

// CountLogs is a helper method to define mock.On call
//   - ctx context.Context
//   - opts model.LogQueryOptions
func (_e *MockLoggingService_Expecter) CountLogs(ctx interface{}, opts interface{}) *MockLoggingService_CountLogs_Call {
	return &MockLoggingService_CountLogs_Call{Call: _e.mock.On("CountLogs", ctx, opts)}
}

func (_c *MockLoggingService_CountLogs_Call) Run(run func(ctx context.Context, opts model.LogQueryOptions)) *MockLoggingService_CountLogs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.LogQueryOptions))
	})
	return _c
}

func (_c *MockLoggingService_CountLogs_Call) Return(_a0 int64, _a1 error) *MockLoggingService_CountLogs_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockLoggingService_CountLogs_Call) RunAndReturn(run func(context.Context, model.LogQueryOptions) (int64, error)) *MockLoggingService_CountLogs_Call {
	_c.Call.Return(run)
	return _c
}

// CreateLog provides a mock function with given fields: ctx, entry
func (_m *MockLoggingService) CreateLog(ctx context.Context, entry *model.LogEntry) error {
	ret := _m.Called(ctx, entry)

	if len(ret) == 0 {
		panic("no return value specified for CreateLog")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.LogEntry) error); ok {
		r0 = rf(ctx, entry)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockLoggingService_CreateLog_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateLog'
type MockLoggingService_CreateLog_Call struct {
	*mock.Call
}

// CreateLog is a helper method to define mock.On call
//   - ctx context.Context
//   - entry *model.LogEntry
func (_e *MockLoggingService_Expecter) CreateLog(ctx interface{}, entry interface{}) *MockLoggingService_CreateLog_Call {
	return &MockLoggingService_CreateLog_Call{Call: _e.mock.On("CreateLog", ctx, entry)}
}

func (_c *MockLoggingService_CreateLog_Call) Run(run func(ctx context.Context, entry *model.LogEntry)) *MockLoggingService_CreateLog_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.LogEntry))
	})
	return _c
}

func (_c *MockLoggingService_CreateLog_Call) Return(_a0 error) *MockLoggingService_CreateLog_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockLoggingService_CreateLog_Call) RunAndReturn(run func(context.Context, *model.LogEntry) error) *MockLoggingService_CreateLog_Call {
	_c.Call.Return(run)
	return _c
}

// CreateLogs provides a mock function with given fields: ctx, entries
func (_m *MockLoggingService) CreateLogs(ctx context.Context, entries []*model.LogEntry) error {
	ret := _m.Called(ctx, entries)

	if len(ret) == 0 {
		panic("no return value specified for CreateLogs")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []*model.LogEntry) error); ok {
		r0 = rf(ctx, entries)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockLoggingService_CreateLogs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateLogs'
type MockLoggingService_CreateLogs_Call struct {
	*mock.Call
}

// CreateLogs is a helper method to define mock.On call
//   - ctx context.Context
//   - entries []*model.LogEntry
func (_e *MockLoggingService_Expecter) CreateLogs(ctx interface{}, entries interface{}) *MockLoggingService_CreateLogs_Call {
	return &MockLoggingService_CreateLogs_Call{Call: _e.mock.On("CreateLogs", ctx, entries)}
}

func (_c *MockLoggingService_CreateLogs_Call) Run(run func(ctx context.Context, entries []*model.LogEntry)) *MockLoggingService_CreateLogs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]*model.LogEntry))
	})
	return _c
}

func (_c *MockLoggingService_CreateLogs_Call) Return(_a0 error) *MockLoggingService_CreateLogs_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockLoggingService_CreateLogs_Call) RunAndReturn(run func(context.Context, []*model.LogEntry) error) *MockLoggingService_CreateLogs_Call {
	_c.Call.Return(run)
	return _c
}

// QueryLogs provides a mock function with given fields: ctx, opts
func (_m *MockLoggingService) QueryLogs(ctx context.Context, opts model.LogQueryOptions) ([]model.LogEntry, error) {
	ret := _m.Called(ctx, opts)

	if len(ret) == 0 {
		panic("no return value specified for QueryLogs")
	}

	var r0 []model.LogEntry
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.LogQueryOptions) ([]model.LogEntry, error)); ok {
		return rf(ctx, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.LogQueryOptions) []model.LogEntry); ok {
		r0 = rf(ctx, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.LogEntry)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.LogQueryOptions) error); ok {
		r1 = rf(ctx, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockLoggingService_QueryLogs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'QueryLogs'
type MockLoggingService_QueryLogs_Call struct {
	*mock.Call
}

// QueryLogs is a helper method to define mock.On call
//   - ctx context.Context
//   - opts model.LogQueryOptions
func (_e *MockLoggingService_Expecter) QueryLogs(ctx interface{}, opts interface{}) *MockLoggingService_QueryLogs_Call {
	return &MockLoggingService_QueryLogs_Call{Call: _e.mock.On("QueryLogs", ctx, opts)}
}

func (_c *MockLoggingService_QueryLogs_Call) Run(run func(ctx context.Context, opts model.LogQueryOptions)) *MockLoggingService_QueryLogs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.LogQueryOptions))
	})
	return _c
}

func (_c *MockLoggingService_QueryLogs_Call) Return(_a0 []model.LogEntry, _a1 error) *MockLoggingService_QueryLogs_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockLoggingService_QueryLogs_Call) RunAndReturn(run func(context.Context, model.LogQueryOptions) ([]model.LogEntry, error)) *MockLoggingService_QueryLogs_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockLoggingService creates a new instance of MockLoggingService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLoggingService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLoggingService {
	mock := &MockLoggingService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
