// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	primitive "go.mongodb.org/mongo-driver/bson/primitive"

	repository "github.com/guttosm/pack-service/internal/repository"
)

// MockPackSizesService is an autogenerated mock type for the PackSizesService type
type MockPackSizesService struct {
	mock.Mock
}

type MockPackSizesService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPackSizesService) EXPECT() *MockPackSizesService_Expecter {
	return &MockPackSizesService_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, sizes, createdBy
func (_m *MockPackSizesService) Create(ctx context.Context, sizes []int, createdBy string) (*repository.PackSizeConfig, error) {
	ret := _m.Called(ctx, sizes, createdBy)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *repository.PackSizeConfig
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []int, string) (*repository.PackSizeConfig, error)); ok {
		return rf(ctx, sizes, createdBy)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []int, string) *repository.PackSizeConfig); ok {
		r0 = rf(ctx, sizes, createdBy)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*repository.PackSizeConfig)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []int, string) error); ok {
		r1 = rf(ctx, sizes, createdBy)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPackSizesService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockPackSizesService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - sizes []int
//   - createdBy string
func (_e *MockPackSizesService_Expecter) Create(ctx interface{}, sizes interface{}, createdBy interface{}) *MockPackSizesService_Create_Call {
	return &MockPackSizesService_Create_Call{Call: _e.mock.On("Create", ctx, sizes, createdBy)}
}

func (_c *MockPackSizesService_Create_Call) Run(run func(ctx context.Context, sizes []int, createdBy string)) *MockPackSizesService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]int), args[2].(string))
	})
	return _c
}

func (_c *MockPackSizesService_Create_Call) Return(_a0 *repository.PackSizeConfig, _a1 error) *MockPackSizesService_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPackSizesService_Create_Call) RunAndReturn(run func(context.Context, []int, string) (*repository.PackSizeConfig, error)) *MockPackSizesService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// GetActive provides a mock function with given fields: ctx
func (_m *MockPackSizesService) GetActive(ctx context.Context) (*repository.PackSizeConfig, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetActive")
	}

	var r0 *repository.PackSizeConfig
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*repository.PackSizeConfig, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *repository.PackSizeConfig); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*repository.PackSizeConfig)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPackSizesService_GetActive_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetActive'
type MockPackSizesService_GetActive_Call struct {
	*mock.Call
}

// GetActive is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockPackSizesService_Expecter) GetActive(ctx interface{}) *MockPackSizesService_GetActive_Call {
	return &MockPackSizesService_GetActive_Call{Call: _e.mock.On("GetActive", ctx)}
}

func (_c *MockPackSizesService_GetActive_Call) Run(run func(ctx context.Context)) *MockPackSizesService_GetActive_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockPackSizesService_GetActive_Call) Return(_a0 *repository.PackSizeConfig, _a1 error) *MockPackSizesService_GetActive_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPackSizesService_GetActive_Call) RunAndReturn(run func(context.Context) (*repository.PackSizeConfig, error)) *MockPackSizesService_GetActive_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, limit
func (_m *MockPackSizesService) List(ctx context.Context, limit int) ([]repository.PackSizeConfig, error) {
	ret := _m.Called(ctx, limit)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []repository.PackSizeConfig
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) ([]repository.PackSizeConfig, error)); ok {
		return rf(ctx, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) []repository.PackSizeConfig); ok {
		r0 = rf(ctx, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]repository.PackSizeConfig)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPackSizesService_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockPackSizesService_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - limit int
func (_e *MockPackSizesService_Expecter) List(ctx interface{}, limit interface{}) *MockPackSizesService_List_Call {
	return &MockPackSizesService_List_Call{Call: _e.mock.On("List", ctx, limit)}
}

func (_c *MockPackSizesService_List_Call) Run(run func(ctx context.Context, limit int)) *MockPackSizesService_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *MockPackSizesService_List_Call) Return(_a0 []repository.PackSizeConfig, _a1 error) *MockPackSizesService_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPackSizesService_List_Call) RunAndReturn(run func(context.Context, int) ([]repository.PackSizeConfig, error)) *MockPackSizesService_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, id, sizes, updatedBy
func (_m *MockPackSizesService) Update(ctx context.Context, id primitive.ObjectID, sizes []int, updatedBy string) (*repository.PackSizeConfig, error) {
	ret := _m.Called(ctx, id, sizes, updatedBy)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *repository.PackSizeConfig
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, primitive.ObjectID, []int, string) (*repository.PackSizeConfig, error)); ok {
		return rf(ctx, id, sizes, updatedBy)
	}
	if rf, ok := ret.Get(0).(func(context.Context, primitive.ObjectID, []int, string) *repository.PackSizeConfig); ok {
		r0 = rf(ctx, id, sizes, updatedBy)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*repository.PackSizeConfig)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, primitive.ObjectID, []int, string) error); ok {
		r1 = rf(ctx, id, sizes, updatedBy)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPackSizesService_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockPackSizesService_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - id primitive.ObjectID
//   - sizes []int
//   - updatedBy string
func (_e *MockPackSizesService_Expecter) Update(ctx interface{}, id interface{}, sizes interface{}, updatedBy interface{}) *MockPackSizesService_Update_Call {
	return &MockPackSizesService_Update_Call{Call: _e.mock.On("Update", ctx, id, sizes, updatedBy)}
}

func (_c *MockPackSizesService_Update_Call) Run(run func(ctx context.Context, id primitive.ObjectID, sizes []int, updatedBy string)) *MockPackSizesService_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(primitive.ObjectID), args[2].([]int), args[3].(string))
	})
	return _c
}

func (_c *MockPackSizesService_Update_Call) Return(_a0 *repository.PackSizeConfig, _a1 error) *MockPackSizesService_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPackSizesService_Update_Call) RunAndReturn(run func(context.Context, primitive.ObjectID, []int, string) (*repository.PackSizeConfig, error)) *MockPackSizesService_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPackSizesService creates a new instance of MockPackSizesService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPackSizesService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPackSizesService {
	mock := &MockPackSizesService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
