// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	model "github.com/guttosm/pack-service/internal/domain/model"
	mock "github.com/stretchr/testify/mock"
)

// MockPackCalculator is an autogenerated mock type for the PackCalculator type
type MockPackCalculator struct {
	mock.Mock
}

type MockPackCalculator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPackCalculator) EXPECT() *MockPackCalculator_Expecter {
	return &MockPackCalculator_Expecter{mock: &_m.Mock}
}

// Calculate provides a mock function with given fields: itemsOrdered
func (_m *MockPackCalculator) Calculate(itemsOrdered int) model.PackResult {
	ret := _m.Called(itemsOrdered)

	if len(ret) == 0 {
		panic("no return value specified for Calculate")
	}

	var r0 model.PackResult
	if rf, ok := ret.Get(0).(func(int) model.PackResult); ok {
		r0 = rf(itemsOrdered)
	} else {
		r0 = ret.Get(0).(model.PackResult)
	}

	return r0
}

// MockPackCalculator_Calculate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Calculate'
type MockPackCalculator_Calculate_Call struct {
	*mock.Call
}

// Calculate is a helper method to define mock.On call
//   - itemsOrdered int
func (_e *MockPackCalculator_Expecter) Calculate(itemsOrdered interface{}) *MockPackCalculator_Calculate_Call {
	return &MockPackCalculator_Calculate_Call{Call: _e.mock.On("Calculate", itemsOrdered)}
}

func (_c *MockPackCalculator_Calculate_Call) Run(run func(itemsOrdered int)) *MockPackCalculator_Calculate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int))
	})
	return _c
}

func (_c *MockPackCalculator_Calculate_Call) Return(_a0 model.PackResult) *MockPackCalculator_Calculate_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPackCalculator_Calculate_Call) RunAndReturn(run func(int) model.PackResult) *MockPackCalculator_Calculate_Call {
	_c.Call.Return(run)
	return _c
}

// CalculateWithPackSizes provides a mock function with given fields: itemsOrdered, packSizes
func (_m *MockPackCalculator) CalculateWithPackSizes(itemsOrdered int, packSizes []int) model.PackResult {
	ret := _m.Called(itemsOrdered, packSizes)

	if len(ret) == 0 {
		panic("no return value specified for CalculateWithPackSizes")
	}

	var r0 model.PackResult
	if rf, ok := ret.Get(0).(func(int, []int) model.PackResult); ok {
		r0 = rf(itemsOrdered, packSizes)
	} else {
		r0 = ret.Get(0).(model.PackResult)
	}

	return r0
}

// MockPackCalculator_CalculateWithPackSizes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CalculateWithPackSizes'
type MockPackCalculator_CalculateWithPackSizes_Call struct {
	*mock.Call
}

// CalculateWithPackSizes is a helper method to define mock.On call
//   - itemsOrdered int
//   - packSizes []int
func (_e *MockPackCalculator_Expecter) CalculateWithPackSizes(itemsOrdered interface{}, packSizes interface{}) *MockPackCalculator_CalculateWithPackSizes_Call {
	return &MockPackCalculator_CalculateWithPackSizes_Call{Call: _e.mock.On("CalculateWithPackSizes", itemsOrdered, packSizes)}
}

func (_c *MockPackCalculator_CalculateWithPackSizes_Call) Run(run func(itemsOrdered int, packSizes []int)) *MockPackCalculator_CalculateWithPackSizes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int), args[1].([]int))
	})
	return _c
}

func (_c *MockPackCalculator_CalculateWithPackSizes_Call) Return(_a0 model.PackResult) *MockPackCalculator_CalculateWithPackSizes_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPackCalculator_CalculateWithPackSizes_Call) RunAndReturn(run func(int, []int) model.PackResult) *MockPackCalculator_CalculateWithPackSizes_Call {
	_c.Call.Return(run)
	return _c
}

// InvalidateCache provides a mock function with no fields
func (_m *MockPackCalculator) InvalidateCache() {
	_m.Called()
}

// MockPackCalculator_InvalidateCache_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InvalidateCache'
type MockPackCalculator_InvalidateCache_Call struct {
	*mock.Call
}

// InvalidateCache is a helper method to define mock.On call
func (_e *MockPackCalculator_Expecter) InvalidateCache() *MockPackCalculator_InvalidateCache_Call {
	return &MockPackCalculator_InvalidateCache_Call{Call: _e.mock.On("InvalidateCache")}
}

func (_c *MockPackCalculator_InvalidateCache_Call) Run(run func()) *MockPackCalculator_InvalidateCache_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockPackCalculator_InvalidateCache_Call) Return() *MockPackCalculator_InvalidateCache_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockPackCalculator_InvalidateCache_Call) RunAndReturn(run func()) *MockPackCalculator_InvalidateCache_Call {
	_c.Run(run)
	return _c
}

// NewMockPackCalculator creates a new instance of MockPackCalculator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPackCalculator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPackCalculator {
	mock := &MockPackCalculator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
