// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockPermissionService is an autogenerated mock type for the PermissionService type
type MockPermissionService struct {
	mock.Mock
}

type MockPermissionService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPermissionService) EXPECT() *MockPermissionService_Expecter {
	return &MockPermissionService_Expecter{mock: &_m.Mock}
}

// GetPermissionIDByResourceAndAction provides a mock function with given fields: ctx, resource, action
func (_m *MockPermissionService) GetPermissionIDByResourceAndAction(ctx context.Context, resource string, action string) string {
	ret := _m.Called(ctx, resource, action)

	if len(ret) == 0 {
		panic("no return value specified for GetPermissionIDByResourceAndAction")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func(context.Context, string, string) string); ok {
		r0 = rf(ctx, resource, action)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockPermissionService_GetPermissionIDByResourceAndAction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPermissionIDByResourceAndAction'
type MockPermissionService_GetPermissionIDByResourceAndAction_Call struct {
	*mock.Call
}

// GetPermissionIDByResourceAndAction is a helper method to define mock.On call
//   - ctx context.Context
//   - resource string
//   - action string
func (_e *MockPermissionService_Expecter) GetPermissionIDByResourceAndAction(ctx interface{}, resource interface{}, action interface{}) *MockPermissionService_GetPermissionIDByResourceAndAction_Call {
	return &MockPermissionService_GetPermissionIDByResourceAndAction_Call{Call: _e.mock.On("GetPermissionIDByResourceAndAction", ctx, resource, action)}
}

func (_c *MockPermissionService_GetPermissionIDByResourceAndAction_Call) Run(run func(ctx context.Context, resource string, action string)) *MockPermissionService_GetPermissionIDByResourceAndAction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockPermissionService_GetPermissionIDByResourceAndAction_Call) Return(_a0 string) *MockPermissionService_GetPermissionIDByResourceAndAction_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPermissionService_GetPermissionIDByResourceAndAction_Call) RunAndReturn(run func(context.Context, string, string) string) *MockPermissionService_GetPermissionIDByResourceAndAction_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPermissionService creates a new instance of MockPermissionService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPermissionService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPermissionService {
	mock := &MockPermissionService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
