// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	bson "go.mongodb.org/mongo-driver/bson"

	mock "github.com/stretchr/testify/mock"

	model "github.com/guttosm/pack-service/internal/domain/model"

	primitive "go.mongodb.org/mongo-driver/bson/primitive"
)

// MockPermissionRepositoryInterface is an autogenerated mock type for the PermissionRepositoryInterface type
type MockPermissionRepositoryInterface struct {
	mock.Mock
}

type MockPermissionRepositoryInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPermissionRepositoryInterface) EXPECT() *MockPermissionRepositoryInterface_Expecter {
	return &MockPermissionRepositoryInterface_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, permission
func (_m *MockPermissionRepositoryInterface) Create(ctx context.Context, permission *model.Permission) error {
	ret := _m.Called(ctx, permission)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Permission) error); ok {
		r0 = rf(ctx, permission)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockPermissionRepositoryInterface_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockPermissionRepositoryInterface_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - permission *model.Permission
func (_e *MockPermissionRepositoryInterface_Expecter) Create(ctx interface{}, permission interface{}) *MockPermissionRepositoryInterface_Create_Call {
	return &MockPermissionRepositoryInterface_Create_Call{Call: _e.mock.On("Create", ctx, permission)}
}

func (_c *MockPermissionRepositoryInterface_Create_Call) Run(run func(ctx context.Context, permission *model.Permission)) *MockPermissionRepositoryInterface_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.Permission))
	})
	return _c
}

func (_c *MockPermissionRepositoryInterface_Create_Call) Return(_a0 error) *MockPermissionRepositoryInterface_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPermissionRepositoryInterface_Create_Call) RunAndReturn(run func(context.Context, *model.Permission) error) *MockPermissionRepositoryInterface_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *MockPermissionRepositoryInterface) Delete(ctx context.Context, id primitive.ObjectID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, primitive.ObjectID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockPermissionRepositoryInterface_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockPermissionRepositoryInterface_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id primitive.ObjectID
func (_e *MockPermissionRepositoryInterface_Expecter) Delete(ctx interface{}, id interface{}) *MockPermissionRepositoryInterface_Delete_Call {
	return &MockPermissionRepositoryInterface_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockPermissionRepositoryInterface_Delete_Call) Run(run func(ctx context.Context, id primitive.ObjectID)) *MockPermissionRepositoryInterface_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(primitive.ObjectID))
	})
	return _c
}

func (_c *MockPermissionRepositoryInterface_Delete_Call) Return(_a0 error) *MockPermissionRepositoryInterface_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPermissionRepositoryInterface_Delete_Call) RunAndReturn(run func(context.Context, primitive.ObjectID) error) *MockPermissionRepositoryInterface_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function with given fields: ctx, id
func (_m *MockPermissionRepositoryInterface) FindByID(ctx context.Context, id primitive.ObjectID) (*model.Permission, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *model.Permission
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, primitive.ObjectID) (*model.Permission, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, primitive.ObjectID) *model.Permission); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Permission)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, primitive.ObjectID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPermissionRepositoryInterface_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockPermissionRepositoryInterface_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id primitive.ObjectID
func (_e *MockPermissionRepositoryInterface_Expecter) FindByID(ctx interface{}, id interface{}) *MockPermissionRepositoryInterface_FindByID_Call {
	return &MockPermissionRepositoryInterface_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *MockPermissionRepositoryInterface_FindByID_Call) Run(run func(ctx context.Context, id primitive.ObjectID)) *MockPermissionRepositoryInterface_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(primitive.ObjectID))
	})
	return _c
}

func (_c *MockPermissionRepositoryInterface_FindByID_Call) Return(_a0 *model.Permission, _a1 error) *MockPermissionRepositoryInterface_FindByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPermissionRepositoryInterface_FindByID_Call) RunAndReturn(run func(context.Context, primitive.ObjectID) (*model.Permission, error)) *MockPermissionRepositoryInterface_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByIDs provides a mock function with given fields: ctx, ids
func (_m *MockPermissionRepositoryInterface) FindByIDs(ctx context.Context, ids []string) ([]*model.Permission, error) {
	ret := _m.Called(ctx, ids)

	if len(ret) == 0 {
		panic("no return value specified for FindByIDs")
	}

	var r0 []*model.Permission
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []string) ([]*model.Permission, error)); ok {
		return rf(ctx, ids)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []string) []*model.Permission); ok {
		r0 = rf(ctx, ids)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Permission)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []string) error); ok {
		r1 = rf(ctx, ids)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPermissionRepositoryInterface_FindByIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByIDs'
type MockPermissionRepositoryInterface_FindByIDs_Call struct {
	*mock.Call
}

// FindByIDs is a helper method to define mock.On call
//   - ctx context.Context
//   - ids []string
func (_e *MockPermissionRepositoryInterface_Expecter) FindByIDs(ctx interface{}, ids interface{}) *MockPermissionRepositoryInterface_FindByIDs_Call {
	return &MockPermissionRepositoryInterface_FindByIDs_Call{Call: _e.mock.On("FindByIDs", ctx, ids)}
}

func (_c *MockPermissionRepositoryInterface_FindByIDs_Call) Run(run func(ctx context.Context, ids []string)) *MockPermissionRepositoryInterface_FindByIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]string))
	})
	return _c
}

func (_c *MockPermissionRepositoryInterface_FindByIDs_Call) Return(_a0 []*model.Permission, _a1 error) *MockPermissionRepositoryInterface_FindByIDs_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPermissionRepositoryInterface_FindByIDs_Call) RunAndReturn(run func(context.Context, []string) ([]*model.Permission, error)) *MockPermissionRepositoryInterface_FindByIDs_Call {
	_c.Call.Return(run)
	return _c
}

// FindByResourceAndAction provides a mock function with given fields: ctx, resource, action
func (_m *MockPermissionRepositoryInterface) FindByResourceAndAction(ctx context.Context, resource string, action string) (*model.Permission, error) {
	ret := _m.Called(ctx, resource, action)

	if len(ret) == 0 {
		panic("no return value specified for FindByResourceAndAction")
	}

	var r0 *model.Permission
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*model.Permission, error)); ok {
		return rf(ctx, resource, action)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *model.Permission); ok {
		r0 = rf(ctx, resource, action)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Permission)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, resource, action)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPermissionRepositoryInterface_FindByResourceAndAction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByResourceAndAction'
type MockPermissionRepositoryInterface_FindByResourceAndAction_Call struct {
	*mock.Call
}

// FindByResourceAndAction is a helper method to define mock.On call
//   - ctx context.Context
//   - resource string
//   - action string
func (_e *MockPermissionRepositoryInterface_Expecter) FindByResourceAndAction(ctx interface{}, resource interface{}, action interface{}) *MockPermissionRepositoryInterface_FindByResourceAndAction_Call {
	return &MockPermissionRepositoryInterface_FindByResourceAndAction_Call{Call: _e.mock.On("FindByResourceAndAction", ctx, resource, action)}
}

func (_c *MockPermissionRepositoryInterface_FindByResourceAndAction_Call) Run(run func(ctx context.Context, resource string, action string)) *MockPermissionRepositoryInterface_FindByResourceAndAction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockPermissionRepositoryInterface_FindByResourceAndAction_Call) Return(_a0 *model.Permission, _a1 error) *MockPermissionRepositoryInterface_FindByResourceAndAction_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPermissionRepositoryInterface_FindByResourceAndAction_Call) RunAndReturn(run func(context.Context, string, string) (*model.Permission, error)) *MockPermissionRepositoryInterface_FindByResourceAndAction_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, filter, limit, skip
func (_m *MockPermissionRepositoryInterface) List(ctx context.Context, filter bson.M, limit int64, skip int64) ([]*model.Permission, error) {
	ret := _m.Called(ctx, filter, limit, skip)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*model.Permission
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, bson.M, int64, int64) ([]*model.Permission, error)); ok {
		return rf(ctx, filter, limit, skip)
	}
	if rf, ok := ret.Get(0).(func(context.Context, bson.M, int64, int64) []*model.Permission); ok {
		r0 = rf(ctx, filter, limit, skip)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Permission)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, bson.M, int64, int64) error); ok {
		r1 = rf(ctx, filter, limit, skip)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPermissionRepositoryInterface_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockPermissionRepositoryInterface_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - filter bson.M
//   - limit int64
//   - skip int64
func (_e *MockPermissionRepositoryInterface_Expecter) List(ctx interface{}, filter interface{}, limit interface{}, skip interface{}) *MockPermissionRepositoryInterface_List_Call {
	return &MockPermissionRepositoryInterface_List_Call{Call: _e.mock.On("List", ctx, filter, limit, skip)}
}

func (_c *MockPermissionRepositoryInterface_List_Call) Run(run func(ctx context.Context, filter bson.M, limit int64, skip int64)) *MockPermissionRepositoryInterface_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(bson.M), args[2].(int64), args[3].(int64))
	})
	return _c
}

func (_c *MockPermissionRepositoryInterface_List_Call) Return(_a0 []*model.Permission, _a1 error) *MockPermissionRepositoryInterface_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPermissionRepositoryInterface_List_Call) RunAndReturn(run func(context.Context, bson.M, int64, int64) ([]*model.Permission, error)) *MockPermissionRepositoryInterface_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, permission
func (_m *MockPermissionRepositoryInterface) Update(ctx context.Context, permission *model.Permission) error {
	ret := _m.Called(ctx, permission)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Permission) error); ok {
		r0 = rf(ctx, permission)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockPermissionRepositoryInterface_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockPermissionRepositoryInterface_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - permission *model.Permission
func (_e *MockPermissionRepositoryInterface_Expecter) Update(ctx interface{}, permission interface{}) *MockPermissionRepositoryInterface_Update_Call {
	return &MockPermissionRepositoryInterface_Update_Call{Call: _e.mock.On("Update", ctx, permission)}
}

func (_c *MockPermissionRepositoryInterface_Update_Call) Run(run func(ctx context.Context, permission *model.Permission)) *MockPermissionRepositoryInterface_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.Permission))
	})
	return _c
}

func (_c *MockPermissionRepositoryInterface_Update_Call) Return(_a0 error) *MockPermissionRepositoryInterface_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPermissionRepositoryInterface_Update_Call) RunAndReturn(run func(context.Context, *model.Permission) error) *MockPermissionRepositoryInterface_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPermissionRepositoryInterface creates a new instance of MockPermissionRepositoryInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPermissionRepositoryInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPermissionRepositoryInterface {
	mock := &MockPermissionRepositoryInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
