// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	bson "go.mongodb.org/mongo-driver/bson"

	mock "github.com/stretchr/testify/mock"

	model "github.com/guttosm/pack-service/internal/domain/model"

	primitive "go.mongodb.org/mongo-driver/bson/primitive"
)

// MockRoleRepositoryInterface is an autogenerated mock type for the RoleRepositoryInterface type
type MockRoleRepositoryInterface struct {
	mock.Mock
}

type MockRoleRepositoryInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRoleRepositoryInterface) EXPECT() *MockRoleRepositoryInterface_Expecter {
	return &MockRoleRepositoryInterface_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, role
func (_m *MockRoleRepositoryInterface) Create(ctx context.Context, role *model.Role) error {
	ret := _m.Called(ctx, role)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Role) error); ok {
		r0 = rf(ctx, role)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRoleRepositoryInterface_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockRoleRepositoryInterface_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - role *model.Role
func (_e *MockRoleRepositoryInterface_Expecter) Create(ctx interface{}, role interface{}) *MockRoleRepositoryInterface_Create_Call {
	return &MockRoleRepositoryInterface_Create_Call{Call: _e.mock.On("Create", ctx, role)}
}

func (_c *MockRoleRepositoryInterface_Create_Call) Run(run func(ctx context.Context, role *model.Role)) *MockRoleRepositoryInterface_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.Role))
	})
	return _c
}

func (_c *MockRoleRepositoryInterface_Create_Call) Return(_a0 error) *MockRoleRepositoryInterface_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRoleRepositoryInterface_Create_Call) RunAndReturn(run func(context.Context, *model.Role) error) *MockRoleRepositoryInterface_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *MockRoleRepositoryInterface) Delete(ctx context.Context, id primitive.ObjectID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, primitive.ObjectID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRoleRepositoryInterface_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockRoleRepositoryInterface_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id primitive.ObjectID
func (_e *MockRoleRepositoryInterface_Expecter) Delete(ctx interface{}, id interface{}) *MockRoleRepositoryInterface_Delete_Call {
	return &MockRoleRepositoryInterface_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockRoleRepositoryInterface_Delete_Call) Run(run func(ctx context.Context, id primitive.ObjectID)) *MockRoleRepositoryInterface_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(primitive.ObjectID))
	})
	return _c
}

func (_c *MockRoleRepositoryInterface_Delete_Call) Return(_a0 error) *MockRoleRepositoryInterface_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRoleRepositoryInterface_Delete_Call) RunAndReturn(run func(context.Context, primitive.ObjectID) error) *MockRoleRepositoryInterface_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function with given fields: ctx, id
func (_m *MockRoleRepositoryInterface) FindByID(ctx context.Context, id primitive.ObjectID) (*model.Role, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *model.Role
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, primitive.ObjectID) (*model.Role, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, primitive.ObjectID) *model.Role); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Role)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, primitive.ObjectID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRoleRepositoryInterface_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockRoleRepositoryInterface_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id primitive.ObjectID
func (_e *MockRoleRepositoryInterface_Expecter) FindByID(ctx interface{}, id interface{}) *MockRoleRepositoryInterface_FindByID_Call {
	return &MockRoleRepositoryInterface_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *MockRoleRepositoryInterface_FindByID_Call) Run(run func(ctx context.Context, id primitive.ObjectID)) *MockRoleRepositoryInterface_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(primitive.ObjectID))
	})
	return _c
}

func (_c *MockRoleRepositoryInterface_FindByID_Call) Return(_a0 *model.Role, _a1 error) *MockRoleRepositoryInterface_FindByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRoleRepositoryInterface_FindByID_Call) RunAndReturn(run func(context.Context, primitive.ObjectID) (*model.Role, error)) *MockRoleRepositoryInterface_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByIDs provides a mock function with given fields: ctx, ids
func (_m *MockRoleRepositoryInterface) FindByIDs(ctx context.Context, ids []string) ([]*model.Role, error) {
	ret := _m.Called(ctx, ids)

	if len(ret) == 0 {
		panic("no return value specified for FindByIDs")
	}

	var r0 []*model.Role
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []string) ([]*model.Role, error)); ok {
		return rf(ctx, ids)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []string) []*model.Role); ok {
		r0 = rf(ctx, ids)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Role)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []string) error); ok {
		r1 = rf(ctx, ids)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRoleRepositoryInterface_FindByIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByIDs'
type MockRoleRepositoryInterface_FindByIDs_Call struct {
	*mock.Call
}

// FindByIDs is a helper method to define mock.On call
//   - ctx context.Context
//   - ids []string
func (_e *MockRoleRepositoryInterface_Expecter) FindByIDs(ctx interface{}, ids interface{}) *MockRoleRepositoryInterface_FindByIDs_Call {
	return &MockRoleRepositoryInterface_FindByIDs_Call{Call: _e.mock.On("FindByIDs", ctx, ids)}
}

func (_c *MockRoleRepositoryInterface_FindByIDs_Call) Run(run func(ctx context.Context, ids []string)) *MockRoleRepositoryInterface_FindByIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]string))
	})
	return _c
}

func (_c *MockRoleRepositoryInterface_FindByIDs_Call) Return(_a0 []*model.Role, _a1 error) *MockRoleRepositoryInterface_FindByIDs_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRoleRepositoryInterface_FindByIDs_Call) RunAndReturn(run func(context.Context, []string) ([]*model.Role, error)) *MockRoleRepositoryInterface_FindByIDs_Call {
	_c.Call.Return(run)
	return _c
}

// FindByName provides a mock function with given fields: ctx, name
func (_m *MockRoleRepositoryInterface) FindByName(ctx context.Context, name string) (*model.Role, error) {
	ret := _m.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for FindByName")
	}

	var r0 *model.Role
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.Role, error)); ok {
		return rf(ctx, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.Role); ok {
		r0 = rf(ctx, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Role)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRoleRepositoryInterface_FindByName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByName'
type MockRoleRepositoryInterface_FindByName_Call struct {
	*mock.Call
}

// FindByName is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockRoleRepositoryInterface_Expecter) FindByName(ctx interface{}, name interface{}) *MockRoleRepositoryInterface_FindByName_Call {
	return &MockRoleRepositoryInterface_FindByName_Call{Call: _e.mock.On("FindByName", ctx, name)}
}

func (_c *MockRoleRepositoryInterface_FindByName_Call) Run(run func(ctx context.Context, name string)) *MockRoleRepositoryInterface_FindByName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRoleRepositoryInterface_FindByName_Call) Return(_a0 *model.Role, _a1 error) *MockRoleRepositoryInterface_FindByName_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRoleRepositoryInterface_FindByName_Call) RunAndReturn(run func(context.Context, string) (*model.Role, error)) *MockRoleRepositoryInterface_FindByName_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, filter, limit, skip
func (_m *MockRoleRepositoryInterface) List(ctx context.Context, filter bson.M, limit int64, skip int64) ([]*model.Role, error) {
	ret := _m.Called(ctx, filter, limit, skip)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*model.Role
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, bson.M, int64, int64) ([]*model.Role, error)); ok {
		return rf(ctx, filter, limit, skip)
	}
	if rf, ok := ret.Get(0).(func(context.Context, bson.M, int64, int64) []*model.Role); ok {
		r0 = rf(ctx, filter, limit, skip)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Role)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, bson.M, int64, int64) error); ok {
		r1 = rf(ctx, filter, limit, skip)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRoleRepositoryInterface_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockRoleRepositoryInterface_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - filter bson.M
//   - limit int64
//   - skip int64
func (_e *MockRoleRepositoryInterface_Expecter) List(ctx interface{}, filter interface{}, limit interface{}, skip interface{}) *MockRoleRepositoryInterface_List_Call {
	return &MockRoleRepositoryInterface_List_Call{Call: _e.mock.On("List", ctx, filter, limit, skip)}
}

func (_c *MockRoleRepositoryInterface_List_Call) Run(run func(ctx context.Context, filter bson.M, limit int64, skip int64)) *MockRoleRepositoryInterface_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(bson.M), args[2].(int64), args[3].(int64))
	})
	return _c
}

func (_c *MockRoleRepositoryInterface_List_Call) Return(_a0 []*model.Role, _a1 error) *MockRoleRepositoryInterface_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRoleRepositoryInterface_List_Call) RunAndReturn(run func(context.Context, bson.M, int64, int64) ([]*model.Role, error)) *MockRoleRepositoryInterface_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, role
func (_m *MockRoleRepositoryInterface) Update(ctx context.Context, role *model.Role) error {
	ret := _m.Called(ctx, role)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Role) error); ok {
		r0 = rf(ctx, role)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRoleRepositoryInterface_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockRoleRepositoryInterface_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - role *model.Role
func (_e *MockRoleRepositoryInterface_Expecter) Update(ctx interface{}, role interface{}) *MockRoleRepositoryInterface_Update_Call {
	return &MockRoleRepositoryInterface_Update_Call{Call: _e.mock.On("Update", ctx, role)}
}

func (_c *MockRoleRepositoryInterface_Update_Call) Run(run func(ctx context.Context, role *model.Role)) *MockRoleRepositoryInterface_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.Role))
	})
	return _c
}

func (_c *MockRoleRepositoryInterface_Update_Call) Return(_a0 error) *MockRoleRepositoryInterface_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRoleRepositoryInterface_Update_Call) RunAndReturn(run func(context.Context, *model.Role) error) *MockRoleRepositoryInterface_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRoleRepositoryInterface creates a new instance of MockRoleRepositoryInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRoleRepositoryInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRoleRepositoryInterface {
	mock := &MockRoleRepositoryInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
