// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/guttosm/pack-service/internal/domain/model"
	mock "github.com/stretchr/testify/mock"

	primitive "go.mongodb.org/mongo-driver/bson/primitive"
)

// MockRoleService is an autogenerated mock type for the RoleService type
type MockRoleService struct {
	mock.Mock
}

type MockRoleService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRoleService) EXPECT() *MockRoleService_Expecter {
	return &MockRoleService_Expecter{mock: &_m.Mock}
}

// FindByID provides a mock function with given fields: ctx, id
func (_m *MockRoleService) FindByID(ctx context.Context, id primitive.ObjectID) (*model.Role, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *model.Role
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, primitive.ObjectID) (*model.Role, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, primitive.ObjectID) *model.Role); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Role)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, primitive.ObjectID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRoleService_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockRoleService_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id primitive.ObjectID
func (_e *MockRoleService_Expecter) FindByID(ctx interface{}, id interface{}) *MockRoleService_FindByID_Call {
	return &MockRoleService_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *MockRoleService_FindByID_Call) Run(run func(ctx context.Context, id primitive.ObjectID)) *MockRoleService_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(primitive.ObjectID))
	})
	return _c
}

func (_c *MockRoleService_FindByID_Call) Return(_a0 *model.Role, _a1 error) *MockRoleService_FindByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRoleService_FindByID_Call) RunAndReturn(run func(context.Context, primitive.ObjectID) (*model.Role, error)) *MockRoleService_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByIDs provides a mock function with given fields: ctx, ids
func (_m *MockRoleService) FindByIDs(ctx context.Context, ids []string) ([]*model.Role, error) {
	ret := _m.Called(ctx, ids)

	if len(ret) == 0 {
		panic("no return value specified for FindByIDs")
	}

	var r0 []*model.Role
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []string) ([]*model.Role, error)); ok {
		return rf(ctx, ids)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []string) []*model.Role); ok {
		r0 = rf(ctx, ids)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Role)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []string) error); ok {
		r1 = rf(ctx, ids)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRoleService_FindByIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByIDs'
type MockRoleService_FindByIDs_Call struct {
	*mock.Call
}

// FindByIDs is a helper method to define mock.On call
//   - ctx context.Context
//   - ids []string
func (_e *MockRoleService_Expecter) FindByIDs(ctx interface{}, ids interface{}) *MockRoleService_FindByIDs_Call {
	return &MockRoleService_FindByIDs_Call{Call: _e.mock.On("FindByIDs", ctx, ids)}
}

func (_c *MockRoleService_FindByIDs_Call) Run(run func(ctx context.Context, ids []string)) *MockRoleService_FindByIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]string))
	})
	return _c
}

func (_c *MockRoleService_FindByIDs_Call) Return(_a0 []*model.Role, _a1 error) *MockRoleService_FindByIDs_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRoleService_FindByIDs_Call) RunAndReturn(run func(context.Context, []string) ([]*model.Role, error)) *MockRoleService_FindByIDs_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRoleService creates a new instance of MockRoleService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRoleService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRoleService {
	mock := &MockRoleService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
