// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	dto "github.com/guttosm/pack-service/internal/domain/dto"
	mock "github.com/stretchr/testify/mock"

	model "github.com/guttosm/pack-service/internal/domain/model"

	primitive "go.mongodb.org/mongo-driver/bson/primitive"
)

// MockTokenService is an autogenerated mock type for the TokenService type
type MockTokenService struct {
	mock.Mock
}

type MockTokenService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTokenService) EXPECT() *MockTokenService_Expecter {
	return &MockTokenService_Expecter{mock: &_m.Mock}
}

// DeleteRefreshToken provides a mock function with given fields: ctx, tokenString
func (_m *MockTokenService) DeleteRefreshToken(ctx context.Context, tokenString string) error {
	ret := _m.Called(ctx, tokenString)

	if len(ret) == 0 {
		panic("no return value specified for DeleteRefreshToken")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, tokenString)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTokenService_DeleteRefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteRefreshToken'
type MockTokenService_DeleteRefreshToken_Call struct {
	*mock.Call
}

// DeleteRefreshToken is a helper method to define mock.On call
//   - ctx context.Context
//   - tokenString string
func (_e *MockTokenService_Expecter) DeleteRefreshToken(ctx interface{}, tokenString interface{}) *MockTokenService_DeleteRefreshToken_Call {
	return &MockTokenService_DeleteRefreshToken_Call{Call: _e.mock.On("DeleteRefreshToken", ctx, tokenString)}
}

func (_c *MockTokenService_DeleteRefreshToken_Call) Run(run func(ctx context.Context, tokenString string)) *MockTokenService_DeleteRefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockTokenService_DeleteRefreshToken_Call) Return(_a0 error) *MockTokenService_DeleteRefreshToken_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTokenService_DeleteRefreshToken_Call) RunAndReturn(run func(context.Context, string) error) *MockTokenService_DeleteRefreshToken_Call {
	_c.Call.Return(run)
	return _c
}

// FindRefreshToken provides a mock function with given fields: ctx, tokenString
func (_m *MockTokenService) FindRefreshToken(ctx context.Context, tokenString string) (*model.Token, error) {
	ret := _m.Called(ctx, tokenString)

	if len(ret) == 0 {
		panic("no return value specified for FindRefreshToken")
	}

	var r0 *model.Token
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.Token, error)); ok {
		return rf(ctx, tokenString)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.Token); ok {
		r0 = rf(ctx, tokenString)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Token)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, tokenString)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTokenService_FindRefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindRefreshToken'
type MockTokenService_FindRefreshToken_Call struct {
	*mock.Call
}

// FindRefreshToken is a helper method to define mock.On call
//   - ctx context.Context
//   - tokenString string
func (_e *MockTokenService_Expecter) FindRefreshToken(ctx interface{}, tokenString interface{}) *MockTokenService_FindRefreshToken_Call {
	return &MockTokenService_FindRefreshToken_Call{Call: _e.mock.On("FindRefreshToken", ctx, tokenString)}
}

func (_c *MockTokenService_FindRefreshToken_Call) Run(run func(ctx context.Context, tokenString string)) *MockTokenService_FindRefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockTokenService_FindRefreshToken_Call) Return(_a0 *model.Token, _a1 error) *MockTokenService_FindRefreshToken_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTokenService_FindRefreshToken_Call) RunAndReturn(run func(context.Context, string) (*model.Token, error)) *MockTokenService_FindRefreshToken_Call {
	_c.Call.Return(run)
	return _c
}

// GenerateTokenPair provides a mock function with given fields: ctx, user
func (_m *MockTokenService) GenerateTokenPair(ctx context.Context, user *model.User) (*dto.TokenPair, error) {
	ret := _m.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for GenerateTokenPair")
	}

	var r0 *dto.TokenPair
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.User) (*dto.TokenPair, error)); ok {
		return rf(ctx, user)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *model.User) *dto.TokenPair); ok {
		r0 = rf(ctx, user)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.TokenPair)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *model.User) error); ok {
		r1 = rf(ctx, user)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTokenService_GenerateTokenPair_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateTokenPair'
type MockTokenService_GenerateTokenPair_Call struct {
	*mock.Call
}

// GenerateTokenPair is a helper method to define mock.On call
//   - ctx context.Context
//   - user *model.User
func (_e *MockTokenService_Expecter) GenerateTokenPair(ctx interface{}, user interface{}) *MockTokenService_GenerateTokenPair_Call {
	return &MockTokenService_GenerateTokenPair_Call{Call: _e.mock.On("GenerateTokenPair", ctx, user)}
}

func (_c *MockTokenService_GenerateTokenPair_Call) Run(run func(ctx context.Context, user *model.User)) *MockTokenService_GenerateTokenPair_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.User))
	})
	return _c
}

func (_c *MockTokenService_GenerateTokenPair_Call) Return(_a0 *dto.TokenPair, _a1 error) *MockTokenService_GenerateTokenPair_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTokenService_GenerateTokenPair_Call) RunAndReturn(run func(context.Context, *model.User) (*dto.TokenPair, error)) *MockTokenService_GenerateTokenPair_Call {
	_c.Call.Return(run)
	return _c
}

// InvalidateAccessToken provides a mock function with given fields: ctx, tokenString
func (_m *MockTokenService) InvalidateAccessToken(ctx context.Context, tokenString string) error {
	ret := _m.Called(ctx, tokenString)

	if len(ret) == 0 {
		panic("no return value specified for InvalidateAccessToken")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, tokenString)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTokenService_InvalidateAccessToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InvalidateAccessToken'
type MockTokenService_InvalidateAccessToken_Call struct {
	*mock.Call
}

// InvalidateAccessToken is a helper method to define mock.On call
//   - ctx context.Context
//   - tokenString string
func (_e *MockTokenService_Expecter) InvalidateAccessToken(ctx interface{}, tokenString interface{}) *MockTokenService_InvalidateAccessToken_Call {
	return &MockTokenService_InvalidateAccessToken_Call{Call: _e.mock.On("InvalidateAccessToken", ctx, tokenString)}
}

func (_c *MockTokenService_InvalidateAccessToken_Call) Run(run func(ctx context.Context, tokenString string)) *MockTokenService_InvalidateAccessToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockTokenService_InvalidateAccessToken_Call) Return(_a0 error) *MockTokenService_InvalidateAccessToken_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTokenService_InvalidateAccessToken_Call) RunAndReturn(run func(context.Context, string) error) *MockTokenService_InvalidateAccessToken_Call {
	_c.Call.Return(run)
	return _c
}

// InvalidateUserTokens provides a mock function with given fields: ctx, userID
func (_m *MockTokenService) InvalidateUserTokens(ctx context.Context, userID primitive.ObjectID) error {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for InvalidateUserTokens")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, primitive.ObjectID) error); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTokenService_InvalidateUserTokens_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InvalidateUserTokens'
type MockTokenService_InvalidateUserTokens_Call struct {
	*mock.Call
}

// InvalidateUserTokens is a helper method to define mock.On call
//   - ctx context.Context
//   - userID primitive.ObjectID
func (_e *MockTokenService_Expecter) InvalidateUserTokens(ctx interface{}, userID interface{}) *MockTokenService_InvalidateUserTokens_Call {
	return &MockTokenService_InvalidateUserTokens_Call{Call: _e.mock.On("InvalidateUserTokens", ctx, userID)}
}

func (_c *MockTokenService_InvalidateUserTokens_Call) Run(run func(ctx context.Context, userID primitive.ObjectID)) *MockTokenService_InvalidateUserTokens_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(primitive.ObjectID))
	})
	return _c
}

func (_c *MockTokenService_InvalidateUserTokens_Call) Return(_a0 error) *MockTokenService_InvalidateUserTokens_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTokenService_InvalidateUserTokens_Call) RunAndReturn(run func(context.Context, primitive.ObjectID) error) *MockTokenService_InvalidateUserTokens_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateAccessToken provides a mock function with given fields: ctx, tokenString
func (_m *MockTokenService) ValidateAccessToken(ctx context.Context, tokenString string) (*dto.Claims, error) {
	ret := _m.Called(ctx, tokenString)

	if len(ret) == 0 {
		panic("no return value specified for ValidateAccessToken")
	}

	var r0 *dto.Claims
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*dto.Claims, error)); ok {
		return rf(ctx, tokenString)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *dto.Claims); ok {
		r0 = rf(ctx, tokenString)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.Claims)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, tokenString)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTokenService_ValidateAccessToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateAccessToken'
type MockTokenService_ValidateAccessToken_Call struct {
	*mock.Call
}

// ValidateAccessToken is a helper method to define mock.On call
//   - ctx context.Context
//   - tokenString string
func (_e *MockTokenService_Expecter) ValidateAccessToken(ctx interface{}, tokenString interface{}) *MockTokenService_ValidateAccessToken_Call {
	return &MockTokenService_ValidateAccessToken_Call{Call: _e.mock.On("ValidateAccessToken", ctx, tokenString)}
}

func (_c *MockTokenService_ValidateAccessToken_Call) Run(run func(ctx context.Context, tokenString string)) *MockTokenService_ValidateAccessToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockTokenService_ValidateAccessToken_Call) Return(_a0 *dto.Claims, _a1 error) *MockTokenService_ValidateAccessToken_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTokenService_ValidateAccessToken_Call) RunAndReturn(run func(context.Context, string) (*dto.Claims, error)) *MockTokenService_ValidateAccessToken_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateRefreshToken provides a mock function with given fields: tokenString
func (_m *MockTokenService) ValidateRefreshToken(tokenString string) (*dto.Claims, error) {
	ret := _m.Called(tokenString)

	if len(ret) == 0 {
		panic("no return value specified for ValidateRefreshToken")
	}

	var r0 *dto.Claims
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*dto.Claims, error)); ok {
		return rf(tokenString)
	}
	if rf, ok := ret.Get(0).(func(string) *dto.Claims); ok {
		r0 = rf(tokenString)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.Claims)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(tokenString)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTokenService_ValidateRefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateRefreshToken'
type MockTokenService_ValidateRefreshToken_Call struct {
	*mock.Call
}

// ValidateRefreshToken is a helper method to define mock.On call
//   - tokenString string
func (_e *MockTokenService_Expecter) ValidateRefreshToken(tokenString interface{}) *MockTokenService_ValidateRefreshToken_Call {
	return &MockTokenService_ValidateRefreshToken_Call{Call: _e.mock.On("ValidateRefreshToken", tokenString)}
}

func (_c *MockTokenService_ValidateRefreshToken_Call) Run(run func(tokenString string)) *MockTokenService_ValidateRefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockTokenService_ValidateRefreshToken_Call) Return(_a0 *dto.Claims, _a1 error) *MockTokenService_ValidateRefreshToken_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTokenService_ValidateRefreshToken_Call) RunAndReturn(run func(string) (*dto.Claims, error)) *MockTokenService_ValidateRefreshToken_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTokenService creates a new instance of MockTokenService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTokenService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTokenService {
	mock := &MockTokenService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
