// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/guttosm/pack-service/internal/domain/model"
	mock "github.com/stretchr/testify/mock"

	primitive "go.mongodb.org/mongo-driver/bson/primitive"
)

// MockTokenRepositoryInterface is an autogenerated mock type for the TokenRepositoryInterface type
type MockTokenRepositoryInterface struct {
	mock.Mock
}

type MockTokenRepositoryInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTokenRepositoryInterface) EXPECT() *MockTokenRepositoryInterface_Expecter {
	return &MockTokenRepositoryInterface_Expecter{mock: &_m.Mock}
}

// CleanupExpired provides a mock function with given fields: ctx
func (_m *MockTokenRepositoryInterface) CleanupExpired(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for CleanupExpired")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTokenRepositoryInterface_CleanupExpired_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CleanupExpired'
type MockTokenRepositoryInterface_CleanupExpired_Call struct {
	*mock.Call
}

// CleanupExpired is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockTokenRepositoryInterface_Expecter) CleanupExpired(ctx interface{}) *MockTokenRepositoryInterface_CleanupExpired_Call {
	return &MockTokenRepositoryInterface_CleanupExpired_Call{Call: _e.mock.On("CleanupExpired", ctx)}
}

func (_c *MockTokenRepositoryInterface_CleanupExpired_Call) Run(run func(ctx context.Context)) *MockTokenRepositoryInterface_CleanupExpired_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockTokenRepositoryInterface_CleanupExpired_Call) Return(_a0 error) *MockTokenRepositoryInterface_CleanupExpired_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTokenRepositoryInterface_CleanupExpired_Call) RunAndReturn(run func(context.Context) error) *MockTokenRepositoryInterface_CleanupExpired_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: ctx, token
func (_m *MockTokenRepositoryInterface) Create(ctx context.Context, token *model.Token) error {
	ret := _m.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Token) error); ok {
		r0 = rf(ctx, token)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTokenRepositoryInterface_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockTokenRepositoryInterface_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - token *model.Token
func (_e *MockTokenRepositoryInterface_Expecter) Create(ctx interface{}, token interface{}) *MockTokenRepositoryInterface_Create_Call {
	return &MockTokenRepositoryInterface_Create_Call{Call: _e.mock.On("Create", ctx, token)}
}

func (_c *MockTokenRepositoryInterface_Create_Call) Run(run func(ctx context.Context, token *model.Token)) *MockTokenRepositoryInterface_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.Token))
	})
	return _c
}

func (_c *MockTokenRepositoryInterface_Create_Call) Return(_a0 error) *MockTokenRepositoryInterface_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTokenRepositoryInterface_Create_Call) RunAndReturn(run func(context.Context, *model.Token) error) *MockTokenRepositoryInterface_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *MockTokenRepositoryInterface) Delete(ctx context.Context, id primitive.ObjectID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, primitive.ObjectID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTokenRepositoryInterface_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockTokenRepositoryInterface_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id primitive.ObjectID
func (_e *MockTokenRepositoryInterface_Expecter) Delete(ctx interface{}, id interface{}) *MockTokenRepositoryInterface_Delete_Call {
	return &MockTokenRepositoryInterface_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockTokenRepositoryInterface_Delete_Call) Run(run func(ctx context.Context, id primitive.ObjectID)) *MockTokenRepositoryInterface_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(primitive.ObjectID))
	})
	return _c
}

func (_c *MockTokenRepositoryInterface_Delete_Call) Return(_a0 error) *MockTokenRepositoryInterface_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTokenRepositoryInterface_Delete_Call) RunAndReturn(run func(context.Context, primitive.ObjectID) error) *MockTokenRepositoryInterface_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteByToken provides a mock function with given fields: ctx, tokenString
func (_m *MockTokenRepositoryInterface) DeleteByToken(ctx context.Context, tokenString string) error {
	ret := _m.Called(ctx, tokenString)

	if len(ret) == 0 {
		panic("no return value specified for DeleteByToken")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, tokenString)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTokenRepositoryInterface_DeleteByToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteByToken'
type MockTokenRepositoryInterface_DeleteByToken_Call struct {
	*mock.Call
}

// DeleteByToken is a helper method to define mock.On call
//   - ctx context.Context
//   - tokenString string
func (_e *MockTokenRepositoryInterface_Expecter) DeleteByToken(ctx interface{}, tokenString interface{}) *MockTokenRepositoryInterface_DeleteByToken_Call {
	return &MockTokenRepositoryInterface_DeleteByToken_Call{Call: _e.mock.On("DeleteByToken", ctx, tokenString)}
}

func (_c *MockTokenRepositoryInterface_DeleteByToken_Call) Run(run func(ctx context.Context, tokenString string)) *MockTokenRepositoryInterface_DeleteByToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockTokenRepositoryInterface_DeleteByToken_Call) Return(_a0 error) *MockTokenRepositoryInterface_DeleteByToken_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTokenRepositoryInterface_DeleteByToken_Call) RunAndReturn(run func(context.Context, string) error) *MockTokenRepositoryInterface_DeleteByToken_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteByUserID provides a mock function with given fields: ctx, userID, tokenType
func (_m *MockTokenRepositoryInterface) DeleteByUserID(ctx context.Context, userID primitive.ObjectID, tokenType string) error {
	ret := _m.Called(ctx, userID, tokenType)

	if len(ret) == 0 {
		panic("no return value specified for DeleteByUserID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, primitive.ObjectID, string) error); ok {
		r0 = rf(ctx, userID, tokenType)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTokenRepositoryInterface_DeleteByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteByUserID'
type MockTokenRepositoryInterface_DeleteByUserID_Call struct {
	*mock.Call
}

// DeleteByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID primitive.ObjectID
//   - tokenType string
func (_e *MockTokenRepositoryInterface_Expecter) DeleteByUserID(ctx interface{}, userID interface{}, tokenType interface{}) *MockTokenRepositoryInterface_DeleteByUserID_Call {
	return &MockTokenRepositoryInterface_DeleteByUserID_Call{Call: _e.mock.On("DeleteByUserID", ctx, userID, tokenType)}
}

func (_c *MockTokenRepositoryInterface_DeleteByUserID_Call) Run(run func(ctx context.Context, userID primitive.ObjectID, tokenType string)) *MockTokenRepositoryInterface_DeleteByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(primitive.ObjectID), args[2].(string))
	})
	return _c
}

func (_c *MockTokenRepositoryInterface_DeleteByUserID_Call) Return(_a0 error) *MockTokenRepositoryInterface_DeleteByUserID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTokenRepositoryInterface_DeleteByUserID_Call) RunAndReturn(run func(context.Context, primitive.ObjectID, string) error) *MockTokenRepositoryInterface_DeleteByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByToken provides a mock function with given fields: ctx, tokenString
func (_m *MockTokenRepositoryInterface) FindByToken(ctx context.Context, tokenString string) (*model.Token, error) {
	ret := _m.Called(ctx, tokenString)

	if len(ret) == 0 {
		panic("no return value specified for FindByToken")
	}

	var r0 *model.Token
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.Token, error)); ok {
		return rf(ctx, tokenString)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.Token); ok {
		r0 = rf(ctx, tokenString)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Token)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, tokenString)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTokenRepositoryInterface_FindByToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByToken'
type MockTokenRepositoryInterface_FindByToken_Call struct {
	*mock.Call
}

// FindByToken is a helper method to define mock.On call
//   - ctx context.Context
//   - tokenString string
func (_e *MockTokenRepositoryInterface_Expecter) FindByToken(ctx interface{}, tokenString interface{}) *MockTokenRepositoryInterface_FindByToken_Call {
	return &MockTokenRepositoryInterface_FindByToken_Call{Call: _e.mock.On("FindByToken", ctx, tokenString)}
}

func (_c *MockTokenRepositoryInterface_FindByToken_Call) Run(run func(ctx context.Context, tokenString string)) *MockTokenRepositoryInterface_FindByToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockTokenRepositoryInterface_FindByToken_Call) Return(_a0 *model.Token, _a1 error) *MockTokenRepositoryInterface_FindByToken_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTokenRepositoryInterface_FindByToken_Call) RunAndReturn(run func(context.Context, string) (*model.Token, error)) *MockTokenRepositoryInterface_FindByToken_Call {
	_c.Call.Return(run)
	return _c
}

// FindByUserID provides a mock function with given fields: ctx, userID, tokenType
func (_m *MockTokenRepositoryInterface) FindByUserID(ctx context.Context, userID primitive.ObjectID, tokenType string) ([]*model.Token, error) {
	ret := _m.Called(ctx, userID, tokenType)

	if len(ret) == 0 {
		panic("no return value specified for FindByUserID")
	}

	var r0 []*model.Token
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, primitive.ObjectID, string) ([]*model.Token, error)); ok {
		return rf(ctx, userID, tokenType)
	}
	if rf, ok := ret.Get(0).(func(context.Context, primitive.ObjectID, string) []*model.Token); ok {
		r0 = rf(ctx, userID, tokenType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Token)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, primitive.ObjectID, string) error); ok {
		r1 = rf(ctx, userID, tokenType)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTokenRepositoryInterface_FindByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByUserID'
type MockTokenRepositoryInterface_FindByUserID_Call struct {
	*mock.Call
}

// FindByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID primitive.ObjectID
//   - tokenType string
func (_e *MockTokenRepositoryInterface_Expecter) FindByUserID(ctx interface{}, userID interface{}, tokenType interface{}) *MockTokenRepositoryInterface_FindByUserID_Call {
	return &MockTokenRepositoryInterface_FindByUserID_Call{Call: _e.mock.On("FindByUserID", ctx, userID, tokenType)}
}

func (_c *MockTokenRepositoryInterface_FindByUserID_Call) Run(run func(ctx context.Context, userID primitive.ObjectID, tokenType string)) *MockTokenRepositoryInterface_FindByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(primitive.ObjectID), args[2].(string))
	})
	return _c
}

func (_c *MockTokenRepositoryInterface_FindByUserID_Call) Return(_a0 []*model.Token, _a1 error) *MockTokenRepositoryInterface_FindByUserID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTokenRepositoryInterface_FindByUserID_Call) RunAndReturn(run func(context.Context, primitive.ObjectID, string) ([]*model.Token, error)) *MockTokenRepositoryInterface_FindByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// IsBlacklisted provides a mock function with given fields: ctx, tokenString
func (_m *MockTokenRepositoryInterface) IsBlacklisted(ctx context.Context, tokenString string) (bool, error) {
	ret := _m.Called(ctx, tokenString)

	if len(ret) == 0 {
		panic("no return value specified for IsBlacklisted")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return rf(ctx, tokenString)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = rf(ctx, tokenString)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, tokenString)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTokenRepositoryInterface_IsBlacklisted_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsBlacklisted'
type MockTokenRepositoryInterface_IsBlacklisted_Call struct {
	*mock.Call
}

// IsBlacklisted is a helper method to define mock.On call
//   - ctx context.Context
//   - tokenString string
func (_e *MockTokenRepositoryInterface_Expecter) IsBlacklisted(ctx interface{}, tokenString interface{}) *MockTokenRepositoryInterface_IsBlacklisted_Call {
	return &MockTokenRepositoryInterface_IsBlacklisted_Call{Call: _e.mock.On("IsBlacklisted", ctx, tokenString)}
}

func (_c *MockTokenRepositoryInterface_IsBlacklisted_Call) Run(run func(ctx context.Context, tokenString string)) *MockTokenRepositoryInterface_IsBlacklisted_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockTokenRepositoryInterface_IsBlacklisted_Call) Return(_a0 bool, _a1 error) *MockTokenRepositoryInterface_IsBlacklisted_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTokenRepositoryInterface_IsBlacklisted_Call) RunAndReturn(run func(context.Context, string) (bool, error)) *MockTokenRepositoryInterface_IsBlacklisted_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTokenRepositoryInterface creates a new instance of MockTokenRepositoryInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTokenRepositoryInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTokenRepositoryInterface {
	mock := &MockTokenRepositoryInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
