// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	bson "go.mongodb.org/mongo-driver/bson"

	mock "github.com/stretchr/testify/mock"

	model "github.com/guttosm/pack-service/internal/domain/model"

	primitive "go.mongodb.org/mongo-driver/bson/primitive"
)

// MockUserRepositoryInterface is an autogenerated mock type for the UserRepositoryInterface type
type MockUserRepositoryInterface struct {
	mock.Mock
}

type MockUserRepositoryInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserRepositoryInterface) EXPECT() *MockUserRepositoryInterface_Expecter {
	return &MockUserRepositoryInterface_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, user
func (_m *MockUserRepositoryInterface) Create(ctx context.Context, user *model.User) error {
	ret := _m.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.User) error); ok {
		r0 = rf(ctx, user)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUserRepositoryInterface_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockUserRepositoryInterface_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - user *model.User
func (_e *MockUserRepositoryInterface_Expecter) Create(ctx interface{}, user interface{}) *MockUserRepositoryInterface_Create_Call {
	return &MockUserRepositoryInterface_Create_Call{Call: _e.mock.On("Create", ctx, user)}
}

func (_c *MockUserRepositoryInterface_Create_Call) Run(run func(ctx context.Context, user *model.User)) *MockUserRepositoryInterface_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.User))
	})
	return _c
}

func (_c *MockUserRepositoryInterface_Create_Call) Return(_a0 error) *MockUserRepositoryInterface_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUserRepositoryInterface_Create_Call) RunAndReturn(run func(context.Context, *model.User) error) *MockUserRepositoryInterface_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *MockUserRepositoryInterface) Delete(ctx context.Context, id primitive.ObjectID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, primitive.ObjectID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUserRepositoryInterface_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockUserRepositoryInterface_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id primitive.ObjectID
func (_e *MockUserRepositoryInterface_Expecter) Delete(ctx interface{}, id interface{}) *MockUserRepositoryInterface_Delete_Call {
	return &MockUserRepositoryInterface_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockUserRepositoryInterface_Delete_Call) Run(run func(ctx context.Context, id primitive.ObjectID)) *MockUserRepositoryInterface_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(primitive.ObjectID))
	})
	return _c
}

func (_c *MockUserRepositoryInterface_Delete_Call) Return(_a0 error) *MockUserRepositoryInterface_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUserRepositoryInterface_Delete_Call) RunAndReturn(run func(context.Context, primitive.ObjectID) error) *MockUserRepositoryInterface_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// FindByEmail provides a mock function with given fields: ctx, email
func (_m *MockUserRepositoryInterface) FindByEmail(ctx context.Context, email string) (*model.User, error) {
	ret := _m.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for FindByEmail")
	}

	var r0 *model.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.User, error)); ok {
		return rf(ctx, email)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.User); ok {
		r0 = rf(ctx, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserRepositoryInterface_FindByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByEmail'
type MockUserRepositoryInterface_FindByEmail_Call struct {
	*mock.Call
}

// FindByEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *MockUserRepositoryInterface_Expecter) FindByEmail(ctx interface{}, email interface{}) *MockUserRepositoryInterface_FindByEmail_Call {
	return &MockUserRepositoryInterface_FindByEmail_Call{Call: _e.mock.On("FindByEmail", ctx, email)}
}

func (_c *MockUserRepositoryInterface_FindByEmail_Call) Run(run func(ctx context.Context, email string)) *MockUserRepositoryInterface_FindByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockUserRepositoryInterface_FindByEmail_Call) Return(_a0 *model.User, _a1 error) *MockUserRepositoryInterface_FindByEmail_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserRepositoryInterface_FindByEmail_Call) RunAndReturn(run func(context.Context, string) (*model.User, error)) *MockUserRepositoryInterface_FindByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// FindByEmailForAuth provides a mock function with given fields: ctx, email
func (_m *MockUserRepositoryInterface) FindByEmailForAuth(ctx context.Context, email string) (*model.User, error) {
	ret := _m.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for FindByEmailForAuth")
	}

	var r0 *model.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.User, error)); ok {
		return rf(ctx, email)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.User); ok {
		r0 = rf(ctx, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserRepositoryInterface_FindByEmailForAuth_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByEmailForAuth'
type MockUserRepositoryInterface_FindByEmailForAuth_Call struct {
	*mock.Call
}

// FindByEmailForAuth is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *MockUserRepositoryInterface_Expecter) FindByEmailForAuth(ctx interface{}, email interface{}) *MockUserRepositoryInterface_FindByEmailForAuth_Call {
	return &MockUserRepositoryInterface_FindByEmailForAuth_Call{Call: _e.mock.On("FindByEmailForAuth", ctx, email)}
}

func (_c *MockUserRepositoryInterface_FindByEmailForAuth_Call) Run(run func(ctx context.Context, email string)) *MockUserRepositoryInterface_FindByEmailForAuth_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockUserRepositoryInterface_FindByEmailForAuth_Call) Return(_a0 *model.User, _a1 error) *MockUserRepositoryInterface_FindByEmailForAuth_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserRepositoryInterface_FindByEmailForAuth_Call) RunAndReturn(run func(context.Context, string) (*model.User, error)) *MockUserRepositoryInterface_FindByEmailForAuth_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function with given fields: ctx, id
func (_m *MockUserRepositoryInterface) FindByID(ctx context.Context, id primitive.ObjectID) (*model.User, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *model.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, primitive.ObjectID) (*model.User, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, primitive.ObjectID) *model.User); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, primitive.ObjectID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserRepositoryInterface_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockUserRepositoryInterface_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id primitive.ObjectID
func (_e *MockUserRepositoryInterface_Expecter) FindByID(ctx interface{}, id interface{}) *MockUserRepositoryInterface_FindByID_Call {
	return &MockUserRepositoryInterface_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *MockUserRepositoryInterface_FindByID_Call) Run(run func(ctx context.Context, id primitive.ObjectID)) *MockUserRepositoryInterface_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(primitive.ObjectID))
	})
	return _c
}

func (_c *MockUserRepositoryInterface_FindByID_Call) Return(_a0 *model.User, _a1 error) *MockUserRepositoryInterface_FindByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserRepositoryInterface_FindByID_Call) RunAndReturn(run func(context.Context, primitive.ObjectID) (*model.User, error)) *MockUserRepositoryInterface_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByIDMinimal provides a mock function with given fields: ctx, id
func (_m *MockUserRepositoryInterface) FindByIDMinimal(ctx context.Context, id primitive.ObjectID) (*model.User, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByIDMinimal")
	}

	var r0 *model.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, primitive.ObjectID) (*model.User, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, primitive.ObjectID) *model.User); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, primitive.ObjectID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserRepositoryInterface_FindByIDMinimal_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByIDMinimal'
type MockUserRepositoryInterface_FindByIDMinimal_Call struct {
	*mock.Call
}

// FindByIDMinimal is a helper method to define mock.On call
//   - ctx context.Context
//   - id primitive.ObjectID
func (_e *MockUserRepositoryInterface_Expecter) FindByIDMinimal(ctx interface{}, id interface{}) *MockUserRepositoryInterface_FindByIDMinimal_Call {
	return &MockUserRepositoryInterface_FindByIDMinimal_Call{Call: _e.mock.On("FindByIDMinimal", ctx, id)}
}

func (_c *MockUserRepositoryInterface_FindByIDMinimal_Call) Run(run func(ctx context.Context, id primitive.ObjectID)) *MockUserRepositoryInterface_FindByIDMinimal_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(primitive.ObjectID))
	})
	return _c
}

func (_c *MockUserRepositoryInterface_FindByIDMinimal_Call) Return(_a0 *model.User, _a1 error) *MockUserRepositoryInterface_FindByIDMinimal_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserRepositoryInterface_FindByIDMinimal_Call) RunAndReturn(run func(context.Context, primitive.ObjectID) (*model.User, error)) *MockUserRepositoryInterface_FindByIDMinimal_Call {
	_c.Call.Return(run)
	return _c
}

// FindByUsername provides a mock function with given fields: ctx, username
func (_m *MockUserRepositoryInterface) FindByUsername(ctx context.Context, username string) (*model.User, error) {
	ret := _m.Called(ctx, username)

	if len(ret) == 0 {
		panic("no return value specified for FindByUsername")
	}

	var r0 *model.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.User, error)); ok {
		return rf(ctx, username)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.User); ok {
		r0 = rf(ctx, username)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, username)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserRepositoryInterface_FindByUsername_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByUsername'
type MockUserRepositoryInterface_FindByUsername_Call struct {
	*mock.Call
}

// FindByUsername is a helper method to define mock.On call
//   - ctx context.Context
//   - username string
func (_e *MockUserRepositoryInterface_Expecter) FindByUsername(ctx interface{}, username interface{}) *MockUserRepositoryInterface_FindByUsername_Call {
	return &MockUserRepositoryInterface_FindByUsername_Call{Call: _e.mock.On("FindByUsername", ctx, username)}
}

func (_c *MockUserRepositoryInterface_FindByUsername_Call) Run(run func(ctx context.Context, username string)) *MockUserRepositoryInterface_FindByUsername_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockUserRepositoryInterface_FindByUsername_Call) Return(_a0 *model.User, _a1 error) *MockUserRepositoryInterface_FindByUsername_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserRepositoryInterface_FindByUsername_Call) RunAndReturn(run func(context.Context, string) (*model.User, error)) *MockUserRepositoryInterface_FindByUsername_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, filter, limit, skip
func (_m *MockUserRepositoryInterface) List(ctx context.Context, filter bson.M, limit int64, skip int64) ([]*model.User, error) {
	ret := _m.Called(ctx, filter, limit, skip)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*model.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, bson.M, int64, int64) ([]*model.User, error)); ok {
		return rf(ctx, filter, limit, skip)
	}
	if rf, ok := ret.Get(0).(func(context.Context, bson.M, int64, int64) []*model.User); ok {
		r0 = rf(ctx, filter, limit, skip)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, bson.M, int64, int64) error); ok {
		r1 = rf(ctx, filter, limit, skip)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserRepositoryInterface_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockUserRepositoryInterface_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - filter bson.M
//   - limit int64
//   - skip int64
func (_e *MockUserRepositoryInterface_Expecter) List(ctx interface{}, filter interface{}, limit interface{}, skip interface{}) *MockUserRepositoryInterface_List_Call {
	return &MockUserRepositoryInterface_List_Call{Call: _e.mock.On("List", ctx, filter, limit, skip)}
}

func (_c *MockUserRepositoryInterface_List_Call) Run(run func(ctx context.Context, filter bson.M, limit int64, skip int64)) *MockUserRepositoryInterface_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(bson.M), args[2].(int64), args[3].(int64))
	})
	return _c
}

func (_c *MockUserRepositoryInterface_List_Call) Return(_a0 []*model.User, _a1 error) *MockUserRepositoryInterface_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserRepositoryInterface_List_Call) RunAndReturn(run func(context.Context, bson.M, int64, int64) ([]*model.User, error)) *MockUserRepositoryInterface_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, user
func (_m *MockUserRepositoryInterface) Update(ctx context.Context, user *model.User) error {
	ret := _m.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.User) error); ok {
		r0 = rf(ctx, user)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUserRepositoryInterface_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockUserRepositoryInterface_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - user *model.User
func (_e *MockUserRepositoryInterface_Expecter) Update(ctx interface{}, user interface{}) *MockUserRepositoryInterface_Update_Call {
	return &MockUserRepositoryInterface_Update_Call{Call: _e.mock.On("Update", ctx, user)}
}

func (_c *MockUserRepositoryInterface_Update_Call) Run(run func(ctx context.Context, user *model.User)) *MockUserRepositoryInterface_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.User))
	})
	return _c
}

func (_c *MockUserRepositoryInterface_Update_Call) Return(_a0 error) *MockUserRepositoryInterface_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUserRepositoryInterface_Update_Call) RunAndReturn(run func(context.Context, *model.User) error) *MockUserRepositoryInterface_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUserRepositoryInterface creates a new instance of MockUserRepositoryInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserRepositoryInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserRepositoryInterface {
	mock := &MockUserRepositoryInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
